### ISSUE TITLE
Timeout sending data Open edX data to Richie

### ISSUE THREAD

**Issue by igobranco** [fccn/richie-openedx-sync#13]
Open edX celery task that synchronizes course information from LMS/Studio to Richie is timing out.

From Sentry it is timing out after 5 seconds. It should be more than enough to Richie update itself.

Changes that need to be made:
1. This celery task shouldn't raise any error;
2. Replace the log error with a log warning;
3. Increase the timeout (from 5 to 20 seconds) and make it configurable;

Screen shot from Sentry with the error:
![Image](https://github.com/fccn/richie-openedx-sync/assets/67018/669ca7ae-b489-4b7d-b022-2eb73cfcdd3d)

```
Error synchronizing course course-v1:INA+EIDCE+2024_T1 to richie site https://www.nau

message
Error synchronizing course course-v1:INA+EIDCE+2024_T1 to richie site https://www.nau.edu.pt/api/v1.0/course-runs-sync/

richie_openedx_sync.tasks
HTTPSConnectionPool(host='www.nau.edu.pt', port=443): Read timed out. (read timeout=5)

richie_openedx_sync.tasks.sync_course_run_information_to_richie

ReadTimeout
 
richie_openedx_sync.tasks.sync_course_run_information_to_richie

HTTPSConnectionPool(host='www.nau.edu.pt', port=443): Read timed out. (read timeout=5)
```

**Comment by igobranco** [comment]
The timeout is already configurable, like:

```yml
RICHIE_OPENEDX_SYNC_COURSE_HOOKS:
  - url: https://some.richie.education/api/v1.0/course-runs-sync/
    secret: my-secret
    timeout: 20
```
